version: '3.8'
services:
  mysql-service:
    container_name: mysql-container
    image: mysql:8.0.28
    ports: 
      - 3307:3306
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: forex_calculator
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      TZ: Asia/Ho_Chi_Minh
    volumes: 
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/etc/mysql/conf.d
      - ./forex.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - calculator
  calculator-container:
    container_name: calculator-container
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8005:8080
    volumes:
      - ./:/app
    environment: 
      TZ: Asia/Ho_Chi_Minh
    depends_on:
      - mysql-service
    networks:
      - calculator
networks:
  calculator:
    name: calculator-app-network
volumes: 
  mysql-springboot-data:
  mysql-springboot-config-deamond: